// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from '@prisma/config';

export default defineConfig({
  migrations: {
    // On indique à Prisma d'utiliser l'outil tsx pour exécuter notre script
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});